import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
* Creating a sidebar enables you to:
- create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation
 
The sidebars can be generated from the filesystem, or explicitly defined here.
 
Create as many sidebars as you want.
*/
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: "category",
      label: "Allgemeines",
      items: [
        {
          type: "autogenerated",
          dirName: "allgemeines",
        },
      ],
    },
    {
      type: "category",
      label: "Theorie",
      items: [
        {
          type: "autogenerated",
          dirName: "theorie",
        },
      ],
    },
    {
      type: "category",
      label: "Projekte",
      items: [
        {
          type: "autogenerated",
          dirName: "projects",
        },
      ],
    },
    {
      type: "category",
      label: "Softwareentwicklung",
      items: [
        {
          type: "autogenerated",
          dirName: "SE",
        },
      ],
    },
    {
      type: "category",
      label: "Tipps & Tricks",
      items: [
        {
          type: "autogenerated",
          dirName: "tipps-tricks",
        },
      ],
    },
    {
      type: "category",
      label: "Tools",
      items: [
        {
          type: "autogenerated",
          dirName: "tools",
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
